export { Hero } from './Hero'
export { Features } from './Features'
export { Installation } from './Installation'
export { LiveDemo } from './LiveDemo'
export { Docs } from './Docs'
export { Changelog } from './Changelog'
export { Footer } from './Footer'
export { Navbar } from './Navbar'
